# Generated by Django 3.0.5 on 2020-04-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_app', '0002_auto_20200424_1940'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='networkuser',
            managers=[
            ],
        ),
    ]
